# Set firewall
- name: Install pve firewall config
  become: true
  ansible.builtin.copy:
    src: proxmox/cluster.fw
    dest: /etc/pve/firewall/cluster.fw
    owner: root
    group: www-data
    mode: '0640'
  notify:
    - restart pve firewall
# Metrics Exporter
- name: Install prometheus-pve-exporter python package
  ansible.builtin.pip:
    name: prometheus-pve-exporter