# Set firewall
- name: Install pve firewall config
  become: true
  ansible.builtin.copy:
    src: proxmox/firewall/cluster.fw
    dest: /etc/pve/firewall/cluster.fw
    owner: root
    group: www-data
    mode: '0640'
  notify:
    - restart pve firewall
- name: Install fabricant-prod firewall config
  become: true
  ansible.builtin.copy:
    src: proxmox/firewall/fabricant-prod.fw
    dest: /etc/pve/firewall/100.fw
    owner: root
    group: www-data
    mode: '0640'
  notify:
    - restart pve firewall
- name: Install pfsense firewall config
  become: true
  ansible.builtin.copy:
    src: proxmox/firewall/pfsense.fw
    dest: /etc/pve/firewall/101.fw
    owner: root
    group: www-data
    mode: '0640'
  notify:
    - restart pve firewall
- name: Install fabricant-ldap firewall config
  become: true
  ansible.builtin.copy:
    src: proxmox/firewall/fabricant-ldap.fw
    dest: /etc/pve/firewall/103.fw
    owner: root
    group: www-data
    mode: '0640'
  notify:
    - restart pve firewall

- name: Create pve group log folder
  ansible.builtin.file:
    path: '{{ansible_env.HOME}}/fabricant-host/.pve-group-logs'
    state: directory
    mode: '0755'
- name: Create pve user log folder
  ansible.builtin.file:
    path: '{{ansible_env.HOME}}/fabricant-host/.pve-user-logs'
    state: directory
    mode: '0755'
- name: Create pve administrators group
  become: true
  ansible.builtin.shell:
    cmd: pveum group add administrators > {{ansible_env.HOME}}/fabricant-host/.pve-group-logs/administrators
    creates: '{{ansible_env.HOME}}/fabricant-host/.pve-group-logs/administrators'
- name: Assign cluster administrator permissions to the newly created administrators group
  become: true
  ansible.builtin.shell:
    cmd: pveum acl modify / --roles Administrator --groups administrators 
- name: Add fabricant-admin to administrators group
  become: true
  ansible.builtin.shell:
    cmd: pveum user add fabricant-admin@pam --groups administrators > {{ansible_env.HOME}}/fabricant-host/.pve-user-logs/fabricant-admin
    creates: '{{ansible_env.HOME}}/fabricant-host/.pve-user-logs/fabricant-admin'
  
- name: Download ostemplate
  become: true
  ansible.builtin.shell:
    cmd: pveam download {{ item["storage"] }} {{ item["image"] }}
    creates: /var/lib/pve/local-btrfs/template/cache/{{ item["image"] }}
  loop: "{{ostemplates}}"