name: Deploy to Fabricant-Host

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Run Ansible Playbook
        run: |
          pushd /home/fabricant-deploy/fabricant-host
          git pull origin main
          source /home/fabricant-deploy/fabricant-host/.venv/bin/activate
          ansible-playbook playbook.yaml
          popd
